# Generated by Django 4.2.7 on 2023-11-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0002_cash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loantype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('payment_period', models.CharField(max_length=255)),
                ('employment_terms', models.CharField(max_length=255)),
                ('security_details', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('loan_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected')], default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='loans', to='Main.group')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.loantype')),
                ('members', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.members')),
            ],
        ),
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=700)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='expenses', to='Main.group')),
            ],
        ),
    ]
