# Generated by Django 4.2.7 on 2023-11-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_remove_cash_name'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('groups', models.ManyToManyField(blank=True, related_name='fine', to='Main.group')),
            ],
        ),
    ]
