# Generated by Django 4.2.7 on 2023-11-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_initial'),
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='group',
        ),
        migrations.AddField(
            model_name='loan',
            name='group',
            field=models.ManyToManyField(to='Main.group'),
        ),
    ]
