# Generated by Django 4.2.7 on 2023-11-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_fine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fine',
            old_name='Name',
            new_name='Full_Name',
        ),
    ]
