# Generated by Django 4.2.7 on 2023-11-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_initial'),
        ('loan', '0002_remove_loan_group_loan_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='group',
        ),
        migrations.AddField(
            model_name='loan',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='loans', to='Main.group'),
        ),
    ]
