# Generated by Django 4.2.7 on 2023-11-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_initial'),
        ('loan', '0003_remove_loan_group_loan_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='groups',
        ),
        migrations.AddField(
            model_name='loan',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='Main.group'),
        ),
    ]
