# Generated by Django 4.2.7 on 2023-11-28 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_initial'),
        ('loan', '0004_remove_loan_groups_loan_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.members'),
        ),
    ]
