# Generated by Django 4.2.7 on 2023-11-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_alter_loan_loan_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_fully_paid',
            field=models.BooleanField(default=False),
        ),
    ]
