# Generated by Django 4.2.7 on 2023-12-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='withdrawal_restriction_amount',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='pin',
        ),
        migrations.AddField(
            model_name='group',
            name='withdrawal_maximum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='withdrawal_minimum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
