# Generated by Django 4.2.7 on 2023-11-27 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_group_chairperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash',
            name='Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
