# Generated by Django 4.2.7 on 2023-12-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_remove_group_withdrawal_restriction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
