# Generated by Django 4.2.7 on 2023-11-27 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_cash_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cash',
            name='Name',
        ),
    ]
