# Generated by Django 4.2.7 on 2023-12-13 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_members_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='pin',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000, message='PIN must be a four-digit number.'), django.core.validators.MaxValueValidator(9999, message='PIN must be a four-digit number.')]),
        ),
    ]
